language: java
before_install: 
  - cd src/parent
  - sudo apt-get install libspatialite-dev
install: mvn -B install -DskipTests=true -Ptravis
script: mvn -B test -PmongoOnlineTests -Ptravis
services: mongodb
notifications:
  email: false
